name: Publish package
on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: intall dependencies
        run: npm install --frozen-lockfile
      - name: build lib
        run: npm run lib
      - name: build docs
        run: npm run docs:prod
      # - name: publish demo
      #   run: npm publish:demo
      - name: publish
        run: npm run publish:lib
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
